main: de.raidcraft.rcupgrades.RCUpgradesPlugin
name: RCUpgrades
version: ${project.version}#${BUILDS_ALL_TIME}
description: Upgrades API.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API]
database: true